[[redirects]]
  from = "/api/*"
  to = ":splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
  
[[headers]]
  for = "/api/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"