[[redirects]]
  from = "/api/*"
  to = "https://example.com/:splat"
  status = 200
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "*", Access-Control-Allow-Methods = "*"}
  force = true
